### ISSUE TITLE
Menu: Save and Open actions are not functional

### ISSUE THREAD

**Issue by nomadbyte** [royvegard/Nano-Basket#12]
I guess, Save and Open actions are not implemented ...yet.

It'd be nice to signal this somehow to anxious users like myself :)

Not sure about your plans with this very nicely designed utility, serializing the config into JSON may be one option how to handle this. Also, it'd be nice to allow some command-line option to quickly import/export the config.

**Comment by royvegard** [comment]
f8bbcb8a873b7d976a73f8b6098b4b71a289f37b implements Save and Open.
The file format is binary serialized with pickle.
