### ISSUE TITLE
TypeError shown when nanoKONTROL device is not found

### ISSUE THREAD

**Issue by nomadbyte** [royvegard/Nano-Basket#13]
This is more about user experience. When nanoKONTROL device is not connected, it'd be nice to report something like "nanoKONTROL Device not found" with some error status.

Currently, the utility crashes with `TypeError` exception.

**Comment by royvegard** [comment]
Fixed in 6b295ae70f26280c024853a028aa66904a619d30

If Nano-Basket doesn't find a nanoKONTROL, it will remain unconnected and it will be the user's job to connect.
