### ISSUE TITLE
Instantly exits out without any GUI or error output

### ISSUE THREAD

**Issue by parkerlreed** [royvegard/Nano-Basket#5]
Arch x86_64
python2 2.7.10-1
pygtk 2.24.0-5

```
[parker@x3720 Nano-Basket]$ python2 nano_basket_gui.py 
[parker@x3720 Nano-Basket]$ 
```

**Comment by royvegard** [comment]
Use
```$ python nano_basket_main.py```
to start it. See [wiki](https://github.com/royvegard/Nano-Basket/wiki/Use).

**Comment by parkerlreed** [comment]
Your README says otherwise :P 

main.py almost works but complains about missing pyalsa. I do have it installed.

````
[parker@x3720 Nano-Basket]$ python2 nano_basket_main.py 
Traceback (most recent call last):
  File "nano_basket_main.py", line 24, in <module>
    from nano_basket_backend import *
  File "/home/parker/build/Nano-Basket/nano_basket_backend.py", line 24, in <module>
    from pyalsa import alsaseq
ImportError: No module named pyalsa
[parker@x3720 Nano-Basket]$ pacman -Q python2-pyalsaaudio-git 
python2-pyalsaaudio-git 0.8.2.r0.g5cbc886-1
````

**Comment by royvegard** [comment]
You have to use the pyalsa package from the alsa-project:
http://www.alsa-project.org/main/index.php/Main_Page

Unfortunately there seems to be other packages named pyalsa (or something similar).

README will be updated.

**Comment by parkerlreed** [comment]
Oh wow forgot all about this project. May have to dig out my little Korg to test again :D
