### ISSUE TITLE
Doesn't work with actual (2020) python

### ISSUE THREAD

**Issue by Olfried2** [royvegard/Nano-Basket#7]
Hello,
I tried to get it work under Ubuntu Linux 20.04. But several python libs are not working.
Maybe it's me, but I cannot find/install some older libs .

Here some informations on my tries.

When starting "normal" (Python 2.7.18) the following error shows up:
<code>
./nano_basket_main.py 
Traceback (most recent call last):
  File "./nano_basket_main.py", line 24, in <module>
    from nano_basket_backend import *
  File "/home/ernst/Music/NanoBasket/nano_basket_backend.py", line 24, in <module>
    from pyalsa import alsaseq
ImportError: No module named pyalsa
</code>
I couldn't find an old "pyalsa"

When I start using **_python3 nano_basket_main.py_** I get:
<code>
Traceback (most recent call last):
  File "nano_basket_main.py", line 33, in <module>
    Midi_Device = Nano_Kontrol_Alsa_Midi_Comm()
  File "/home/ernst/Music/NanoBasket/nano_basket_backend.py", line 267, in __init__
    self.Event = alsaseq.SeqEvent(alsaseq.SEQ_EVENT_SYSEX)
OverflowError: Python int too large to convert to C long
</code>
Now I'm out, I found some informations describing how to fix such an error, but that's outside my abilities.
In the file nano_basket_gui.py i commented line 24  "_pygtk.require('2.0')_" to get rid of some messages asking for it
but I didn't get an old pygtk.

**Comment by maks** [comment]
@Olfried2 you'll definitely need to use python2 not 3.
The error mesg that you are getting is that the pyalsa module is missing. 
On Manjaro I was able to get it installed by following [these instructions](https://freesoftwaremusic.wordpress.com/2014/07/28/nano-basket/comment-page-1/#comment-262) though on Ubuntu you might be able to install pyalsa via apt too. Its not provided in those instructions, but here is the link to the page with the pyalsa [ource download](https://www.alsa-project.org/wiki/Download) if you end up following those instructions.

**Comment by royvegard** [comment]
@Olfried2, I have updated to use python3 only and PyGObject. The README has also been updated. It can be a bit tricky to install pyalsa, since it is not available from pypi, but I believe the popular distributions have a package for it.

**Comment by nomadbyte** [comment]
> ...It can be a bit tricky to install pyalsa

I went the Python3 route on the older Ubuntu 18.04; there's no `python3-pyalsa` available from the Ubuntu distro repo (unlike with Ubuntu 20.04 and later).

To install `pyalsa` on Python3 manually:

- download the source package from Alsa repo (e.g. [pyalsa-1.1.6](https://www.alsa-project.org/files/pub/pyalsa/pyalsa-1.1.6.tar.bz2))
- install from the extracted source (there's `setup.py` file) 
```
pip3 install .
```

This appears to work, at least with the old Python 3.6.9.
