### ISSUE TITLE
Nanokontrol2

### ISSUE THREAD

**Issue by Da-Boom** [royvegard/Nano-Basket#8]
Is it possible to update this for the Nanokontrol 2? - the software for it currently only works in windows, it wont even install on Linux/wine - the installer fails to initialize.
 (i have to use a VM or reboot to windows to edit the buttons rn, which is a hassle)
 
 might also be a nice idea to update for python3..

**Comment by Da-Boom** [comment]
EDIT: I got the software installed... it works so long as i dont have the JACK sound server active

Still would however be nice to have a more native option.

**Comment by royvegard** [comment]
Unfortunately I don't have the nanoKONTROL2 hardware, so i think testing will be difficult. On the bright side Korg has made available the MIDI implementation document for the nanoKONTROL2, so I should be able to implement for nanoKONTROL2 too. @Da-Boom, I'm assuming that you own a nanoKONTROL2, would you be willing to test?

**Comment by Da-Boom** [comment]
I did own one, however it died due to dust getting into the sliders, so I replaced it with an AKAI APC Mini
